version: '3'
services:
  app:
    container_name: uploader_app
    restart: always
    build: .
    environment:
      PORT: 80
    ports:
      - 80:80
    volumes:
      - ./app-data:/usr/src/app/files
    # https://stackoverflow.com/a/50108745/7422308
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn run setup && yarn start'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: uploader
    ports:
      - 5432:5432
    # https://stackoverflow.com/a/41650891/7422308
    volumes:
      - ./app-data:/var/lib/postgresql/data